set_property LOC MMCME3_ADV_X0Y1 [get_cells -hierarchical -filter NAME=~*mmcme3_adv_inst]
set_property LOC BUFGCE_X0Y26 [get_cells -hierarchical -filter NAME=~*clkout1_buf]
set_property LOC BUFGCE_X1Y56 [get_cells -hierarchical -filter NAME=~*U0/No_Dbg_Reg_Access.BUFG_DRCK/Using_FPGA.Native]
set_property IOSTANDARD LVDS [get_ports default_sysclk_300_clk_p]
set_property IOSTANDARD LVDS [get_ports default_sysclk_300_clk_n]
set_property PACKAGE_PIN AK17 [get_ports default_sysclk_300_clk_p]
set_property PACKAGE_PIN AK16 [get_ports default_sysclk_300_clk_n]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN AN8 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_txd]
set_property PACKAGE_PIN K26 [get_ports rs232_uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_rxd]
set_property PACKAGE_PIN G25 [get_ports rs232_uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[0]}]
set_property PACKAGE_PIN AP8 [get_ports {led_8bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[1]}]
set_property PACKAGE_PIN H23 [get_ports {led_8bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[2]}]
set_property PACKAGE_PIN P20 [get_ports {led_8bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[3]}]
set_property PACKAGE_PIN P21 [get_ports {led_8bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[4]}]
set_property PACKAGE_PIN N22 [get_ports {led_8bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[5]}]
set_property PACKAGE_PIN M22 [get_ports {led_8bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[6]}]
set_property PACKAGE_PIN R23 [get_ports {led_8bits_tri_o[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_8bits_tri_o[7]}]
set_property PACKAGE_PIN P23 [get_ports {led_8bits_tri_o[7]}]
